Repository slick/slick, pull requests merged in 2022-08, with the labels that each got.

#2522 Update postgresql to 42.4.2
  project/Dependencies.scala
Labels: build

#2525 Fix URL of sample repos
  project/Docs.scala
Labels: topic:documentation

#2527 Docs improvements
  project/Docs.scala
Labels: topic:documentation, build

#2532 Update postgresql to 42.5.0
  project/Dependencies.scala
Labels: build

#2534 Update sqlite-jdbc to 3.39.2.1
  project/Dependencies.scala
Labels: build
