Repository slick/slick, pull requests merged in 2023-03, with the labels that each got.

#2677 Update logback-classic to 1.3.6
  project/Dependencies.scala
Labels: build

#2693 Remove HList features
  slick-codegen/src/main/scala/slick/codegen/AbstractSourceCodeGenerator.scala
  slick-testkit/src/main/scala/com/typesafe/slick/testkit/tests/InsertTest.scala
  slick-testkit/src/main/scala/com/typesafe/slick/testkit/tests/JdbcMapperTest.scala
  slick-testkit/src/test/scala/slick/test/collection/heterogenous/HListTest.scala
  slick-testkit/src/test/scala/slick/test/collection/heterogenous/NatTest.scala
  slick/src/main/scala/slick/collection/heterogeneous/HList.scala
  slick/src/main/scala/slick/collection/heterogeneous/Nat.scala
  slick/src/main/scala/slick/collection/heterogeneous/TypedFunction.scala
  slick/src/main/scala/slick/collection/heterogeneous/syntax.scala
Labels: release-highlight

#2697 OracleProfile: restore parentheses
  slick/src/main/scala/slick/jdbc/OracleProfile.scala
Labels: bug

#2694 Line breaks after infix operator
  slick/src/main/scala/slick/jdbc/HsqldbProfile.scala
  slick/src/main/scala/slick/jdbc/OracleProfile.scala
  slick/src/main/scala/slick/jdbc/PostgresProfile.scala
  slick/src/main/scala/slick/jdbc/SQLServerProfile.scala
Labels: refactor
